### ISSUE TITLE
Disable upgrade service

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT-Packer#19]
When the (Google) image is started, it runs the `unattended-upgrade` service to install latest security updates and such. The older the image is, the longer this will take. So it could happen that in the first minutes of a load test XLT competes with the update service for system resources. This may cause unexpected and therefore hard-to-explain effects in the load test results. Hence, we should disable or simply uninstall this upgrade service. We also need to check if the AWS image is affected as well.

**Comment by h-arlt** [comment]
It's very likely that AWS images are affected as well since both share the same code base and OS.

**Comment by h-arlt** [comment]
Done.

**Comment by jowerner** [comment]
Looks good, thanks.
