### ISSUE TITLE
Support creating XLT docker images

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT-Packer#5]
`packer` does not only support creating images for various cloud providers, but also docker images. We should add a packer script that uses the docker builder and adjust our XLT image setup scripts if needed.

**Comment by jowerner** [comment]
The docker image build mirrors the build of the regular native cloud images. However, some steps do not apply while others are to be done instead. Hence, the docker build has got an own copy of `setup-image.sh`.

**Comment by h-arlt** [comment]
Looks good to me. Merged into master.
