### ISSUE TITLE
Remove ability to prepare multiple independent XLT installations

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT-Packer#6]
The ability to have multiple independent XLT installations is a relic of those times when XLT was able to run only one agent process per agent controller. These times have long gone. We can simplify the `start-xlt.sh` script such that XLT is installed only once.

**Comment by h-arlt** [comment]
Done.

**Comment by jowerner** [comment]
Please see my comments at the commit. The one with the password replacement stuff is critical.

**Comment by h-arlt** [comment]
Fixed. Will make use of feature branches next time to avoid breaking changes in master.
